# Generated by Django 3.2.6 on 2021-08-14 09:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=200, verbose_name='question name, describing its essence')),
                ('question_text', models.CharField(max_length=200)),
                ('question_answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=4, verbose_name='list of four answers for the question')),
                ('complexity', models.CharField(choices=[('H', 'hard'), ('M', 'medium'), ('E', 'easy')], max_length=1)),
                ('hint', models.CharField(max_length=200, null=True, verbose_name='a hint to a question to help answer it')),
            ],
            options={
                'ordering': ['-complexity'],
            },
        ),
    ]
