# Generated by Django 3.2.6 on 2021-08-19 17:30

import appearance.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appearance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_author',
            field=models.ForeignKey(blank=True, default=appearance.models.UserManager.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='which user the question belongs to'),
        ),
    ]
