# Generated by Django 3.2.6 on 2021-08-14 10:02

from django.db import migrations


def create_data(apps, schema_editor):
    question = apps.get_model('appearance', 'Question')
    question(
        question_name='Груз',
        question_text='Сколько лет Грузу?',
        question_answers=['1', '2', '3', '4'],
        complexity='E',
    ).save()
    question(
        question_name='МС',
        question_text='Сколько ног у МС?',
        question_answers=['1', '2', '3', '4'],
        complexity='H',
        hint='2 or 4'
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('appearance', '0002_alter_question_options'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
