# Generated by Django 3.2.6 on 2021-08-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.CharField(default='Общие знания', max_length=200, verbose_name='which group the question belongs to'),
        ),
    ]
