# Generated by Django 3.2.6 on 2021-08-20 06:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='matvey-age', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='slug',
            field=models.SlugField(default='without-category', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='a hint to a question to help answer it'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), size=4, verbose_name='list of four answers for the question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='question name, describing its essence'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='category_name',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='name of category, like Преподаватели'),
        ),
    ]
