# Generated by Django 3.2.6 on 2021-08-20 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import legends.apps.appearance.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appearance', '0002_auto_20210820_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, default=legends.apps.appearance.models.QuestionCategory.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='questions', to='appearance.questioncategory', verbose_name='which category the question belongs to'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_author',
            field=models.ForeignKey(blank=True, default=legends.apps.appearance.models.UserManager.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='which user the question belongs to'),
        ),
    ]
