# Generated by Django 3.2.6 on 2021-08-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0003_auto_20210820_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='true_answer',
            field=models.CharField(default=1, max_length=128, verbose_name='true answer to a question, "question answers" contains it'),
            preserve_default=False,
        ),
    ]
